[package]
name = "pyqrlew"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyqrlew"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["abi3-py38"] }
qrlew = "0.1.9"
qrlew-sarus = "0.2.2"
serde_json = "1.0.96"
