[package]
name = "pyqrlew"
version = "0.3.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyqrlew"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["abi3-py38"] }
qrlew = "0.3.8"
qrlew-sarus = "0.3"
serde_json = "1.0"
